package backend;

public class Atividade {
	
	// CATEGORIAS
	public static String[] catAdm = {
			"CONTROLE",
			"DOCUMENTAÇÃO",
			"ORÇAMENTO E GESTÃO",
			"RETRABALHOS E MELHORIAS",
			"GERAL"
	};
	public static String[] catProj = {
			"DESENVOLVIMENTO",
			"VISITA TÉCNICA",
			"ELABORAÇÃO",
			"GESTÃO E ACOMPANHAMENTO",
			"DOCUMENTAÇÃO",
			"RETRABALHOS E MELHORIAS",
			"GERAL"
	};
	public static String[] catEng = {
			"DESENVOLVIMENTO",
			"VISITA TÉCNICA",
			"ELABORAÇÃO",
			"GESTÃO E ACOMPANHAMENTO",
			"DOCUMENTAÇÃO",
			"RETRABALHOS E MELHORIAS",
			"GERAL"
	};
	public static String[] catEle = {
			"MONTAGEM",
			"TESTES",
			"IDENTIFICAÇÃO",
			"DOCUMENTOS",
			"ORÇAMENTO",
			"GESTÃO E ACOMPANHAMENTO",
			"RETRABALHOS E MELHORIAS",
			"GERAL"
	};
	public static String[] catProg = {
			"PROGRAMAÇÃO",
			"PROJETO ELÉTRICO",
			"DOCUMENTAÇÃO",
			"ORÇAMENTO",
			"GESTÃO DE PROJETO",
			"RETRABALHOS E MELHORIAS",
			"GERAL"
	};
	public static String[] catMec = {
			"MONTAGEM",
			"USINAGEM",
			"AJUSTES",
			"CALDEIRARIA",
			"DOCUMENTAÇÃO",
			"ORÇAMENTO",
			"GESTÃO DE PROJETO",
			"RETRABALHOS E MELHORIAS",
			"GERAL"
	};

	//SUB-CATEGORIAS
	public static String[][] subCatAdm = {
			{"CONTROLE DE COMPRAS", "CONTROLE DE DEMANDA", "CONTROLE DE HORAS"},
			{"DOCUMENTAÇÃO DE MÁQUINA", "DOCUMENTAÇÃO", "PROJETO"},
			{"ORÇAMENTO", "GESTÃO DE PROJETO", "FOLLOW UP E DEMANDA"},
			{"RETRABALHO INTERNO", "RETRABALHO EXTERNO", "MELHORIAS"},
			{"TESTES E PROTÓTIPOS", "MANUTENÇÃO", "ALMOXARIFADO", "5S", "NÃO PRODUTIVOS", "AUSÊNCIA"}
	};
	public static String[][] subCatProj = {
			{"DESENVOLVIMENTO DE PROJETO", "CONTROLE DE PROJETO", "LISTA DE PEÇAS", "DESIGN REVIEW"},
			{"VISITA TÉCNICA"},
			{"ELABORAÇÃO DE TERMO DE ABERTURA", "ELABORAÇÃO DE ESCOPO"},
			{"ACOMPANHAMENTO DE MONTAGEM", "ACOMPANHAMENTO DE S.A.", "ACOMPANHAMENTO DE EVENTO", "ACOMPANHAMENTO DE PESSOAL", "GESTÃO DE PROJETO", "FOLLOW UP E DEMANDA"}, //[2]
			{"DOCUMENTAÇÃO DE MÁQUINA", "DOCUMENTAÇÃO", "ORÇAMENTO"},
			{"RETRABALHO INTERNO", "RETRABALHO EXTERNO", "MELHORIAS"},
			{"TESTES E PROTÓTIPOS", "MANUTENÇÃO", "ALMOXARIFADO", "5S", "NÃO PRODUTIVOS", "AUSÊNCIA"}
	};
	public static String[][] subCatEng = {
			{"DESENVOLVIMENTO DE PROJETO", "CONTROLE DE PROJETO", "LISTA DE PEÇAS", "DESIGN REVIEW"},
			{"VISITA TÉCNICA"},
			{"ELABORAÇÃO DE TERMO DE ABERTURA", "ELABORAÇÃO DE ESCOPO"},
			{"ACOMPANHAMENTO DE MONTAGEM", "ACOMPANHAMENTO DE S.A.", "ACOMPANHAMENTO DE EVENTO", "ACOMPANHAMENTO DE PESSOAL", "GESTÃO DE PROJETO", "FOLLOW UP E DEMANDA"}, //[2]
			{"DOCUMENTAÇÃO DE MÁQUINA", "DOCUMENTAÇÃO", "ORÇAMENTO"},
			{"RETRABALHO INTERNO", "RETRABALHO EXTERNO", "MELHORIAS"},
			{"TESTES E PROTÓTIPOS", "MANUTENÇÃO", "ALMOXARIFADO", "5S", "NÃO PRODUTIVOS", "AUSÊNCIA"}
			//[7]
	};
	public static String[][] subCatEle = {
			{"MONTAGEM DE PAINEL ELÉTRICO", "MONTAGEM DE MÁQUINA", "MONTAGEM GERAL"},
			{"TESTES"},
			{"IDENTIFICAÇÃO DE MÁQUINAS", "IDENTIFICAÇÃO DE PAINEL ELÉTRICO"},
			{"ESQUEMA ELÉTRICO", "LISTA DE PEÇAS", "DOCUMENTAÇÃO"},
			{"ORÇAMENTO"},
			{"GESTÃO DE PROJETO", "ACOMPANHAMENTO DE S.A.", "ACOMPANHAMENTO DE PRODUÇÃO", "ACOMPANHAMENTO DE FORNCEDOR", "ACOMPANHAMENTO DE EVENTO", "ACOMPANHAMENTO DE MONTAGEM"},
			{"RETRABALHO INTERNO", "RETRABALHO EXTERNO", "MELHORIAS"},
			{"TESTES E PROTÓTIPOS", "MANUTENÇÃO", "ALMOXARIFADO", "5S", "NÃO PRODUTIVOS", "AUSÊNCIA"}
	};
	public static String[][] subCatProg = {
			{"PROGRAMAÇÃO", "DESENVOLVIMENTO DE PROGRAMA", "AJUSTE DE PROGRAMA", "AUXÍLIO EM PROGRAMAÇÃO", "REALIZAÇÃO DE BACKUP"},
			{"PROJETO ELÉTRICO", "CORREÇÃO DE PROJETO ELÉTRICO"},
			{"DOCUMENTAÇÃO"},
			{"ORÇAMENTO"},
			{"GESTÃO DE PROJETO"},
			{"RETRABALHO INTERNO", "RETRABALHO EXTERNO", "MELHORIAS"},
			{"TESTES E PROTÓTIPOS", "MANUTENÇÃO", "ALMOXARIFADO", "5S", "NÃO PRODUTIVOS", "AUSÊNCIA"}
	};
	public static String[][] subCatMec = {
			{"MONTAGEM GERAL", "MONTAGEM DE SISTEMA PNEUMÁTICO", "MONTAGEM DE COMPONENTES"},
			{"USINAGEM FRESADORA", "USINAGEM TORNO", "USINAGEM FURADEIRA", "USINAGEM GERAL"},
			{"AJUSTES"},
			{"CALDEIRARIA - CHAPAS", "CALDEIRARIA - CORTE", "CALDEIRARIA - DOBRA", "CALDEIRARIA - SOLDA", "CALDEIRARIA - TRAÇAGEM"},
			{"DOCUMENTAÇÃO", "LISTA DE MATERIAIS"},
			{"ORÇAMENTO"},
			{"GESTÃO DE PROJETO"},
			{"RETRABALHO INTERNO", "RETRABALHO EXTERNO", "MELHORIAS"},
			{"TESTES E PROTÓTIPOS", "MANUTENÇÃO", "ALMOXARIFADO", "5S", "NÃO PRODUTIVOS", "AUSÊNCIA"}
	};
}